### ISSUE TITLE
Investigate activation functions

### ISSUE THREAD

**Issue by knkski** [knkski/atai#5]
Right now we're using ReLU for our activation layers because it [works pretty well](https://www.quora.com/What-is-special-about-rectifier-neural-units-used-in-NN-learning). However, we should test the alternatives and make a nice pretty graph that we could present:

https://keras.io/activations/

**Comment by ykq1004** [comment]
based on this paper, https://arxiv.org/pdf/1511.07289v1.pdf, RELU seems to work better than relu or leakyRelu, tested out on the GPU train?

**Comment by knkski** [comment]
@ziziyue: That seems accurate. This graph shows the effects of different activation functions on a relatively simple network:

![image](https://user-images.githubusercontent.com/20422884/32309061-1e06b486-bf57-11e7-84ba-222d6ed94f26.png)

From left to right, the activation functions used were ELU, Leaky ReLU, PReLU, and ReLU. They all converged to very close to the same value, but ELU converged much faster than the others.

Closing this issue, as it looks like ELU is a clear winner.
